### PR TITLE
Updated FormType for Symfony 3.

### PR DESCRIPTION
**Pull request by iisisrael**
Removed the `getName()` method, updated the parent name to the fully qualified class, and changed `setDefaultOptions()` to `configureOptions()`.

The parent class name is in the format of `Namespace\ClassName` instead of `ClassName::class` for < PHP 5.5.

### CODE REVIEW

**Comment by iisisrael** [comment]
All tests pass when `symfony-test` requirement is updated to [this version](https://github.com/eymengunay/symfony-test/pull/2).

**Comment by peschee** [comment]
Any updates on this PR?

**Comment by eymengunay** [comment]
Oops, sorry about that! I have completely forgotten about this pr.

I've merged both this and https://github.com/eymengunay/symfony-test/pull/2

Thank you @iisisrael and @peschee

**Comment by peschee** [comment]
@eymengunay Did you tag from `master`? I still have `setDefaultOptions` instead of `configureOptions` in `HoneypotType.php`

**Comment by eymengunay** [comment]
@peschee, No I've tagged from c17675f, the last commit before symfony 3 changes were introduced.

**Comment by peschee** [comment]
Ah yes, all good, saw that now. Thanks.

**Pull request merged**
